<!-- Header.php -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="Index.php" title="Click to go to home">
            <img src="Images/Logo.png" alt="ASC Motors Logo" style="height: 40px; margin-right: 10px;">
            ASC Motors
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav gap-3">
                <li class="nav-item">
                    <a class="nav-link" href="Index.php">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="Product.php" title="Click to go to products">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="Gallery.php" title="Click to go to gallery">Gallery</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="Cart.php"  title="Click to go to cart"><i class="bi bi-cart"></i> Cart</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-primary" href="Login.php" title="Click to login">Login</a>
                    <a class="btn btn-primary" href="Login.php" title="Click to logout">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
